import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowRight,Check} from 'lucide-react';
import {CTA,ProductGrid} from '@/components/ui';
import {products,solutions} from '@/lib/data';

export function generateStaticParams(){return solutions.map(s=>({slug:s.slug}))}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const s=solutions.find(x=>x.slug===params.slug);return s?{title:`${s.title} in Lagos, Nigeria`,description:s.summary,alternates:{canonical:`/solutions/${s.slug}`}}:{}}
export default function Page({params}:{params:{slug:string}}){const s=solutions.find(x=>x.slug===params.slug);if(!s)notFound();const recommended=products.filter(p=>s.slug.includes('cctv')?p.category==='security':s.slug.includes('wifi')||s.slug.includes('wireless')?p.category==='wireless':p.category==='networking').slice(0,3);return <main><section className="pageHero"><div className="container"><p className="overline"><Link href="/solutions">Solutions</Link> / {s.title}</p><h1>{s.title}</h1><p>{s.summary}</p><div className="heroActions"><Link className="btn primary" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><Link className="btn" href="/products">Browse Products</Link></div></div></section><section className="section"><div className="container"><div className="sectionHead"><div><p className="overline">The requirement</p><h2>Infrastructure has to work<br/>as one system.</h2></div><p>{s.problem}</p></div><div className="trustGrid">{s.points.map(point=><article className="trustPoint" key={point}><Check size={20}/><div><h3>{point}</h3><p>Specified against the site, use case, compatibility requirements and future growth.</p></div></article>)}</div></div></section><section className="section soft"><div className="container"><div className="sectionHead"><div><p className="overline">Relevant infrastructure</p><h2>Products for this<br/>type of deployment.</h2></div><p>These are representative catalogue items. Exact models and specifications are confirmed during quotation.</p></div><ProductGrid items={recommended}/></div></section><section className="section"><div className="container"><div className="sectionHead"><div><p className="overline">Ideal environments</p><h2>Where this solution fits.</h2></div></div><div className="workflow">{s.industries.map((industry,i)=><article key={industry}><span>0{i+1}</span><h3>{industry}</h3><p className="muted">Discuss the site requirements with Fingaz before selecting equipment.</p></article>)}</div></div></section><CTA/></main>}
