import Link from 'next/link';
import {ArrowRight,ClipboardCheck,Headphones,MapPin,ShieldCheck,ShoppingBag,Wifi} from 'lucide-react';
import {contact,whatsapp} from '@/lib/data';

const promises=[
 {icon:<MapPin/>,title:'Lagos sourcing presence',copy:'Based around Computer Village, Ikeja, with practical market access for technology hardware sourcing.'},
 {icon:<Wifi/>,title:'Infrastructure focus',copy:'Networking, routers, wireless, CCTV, switches, cabling and access-control hardware for business use.'},
 {icon:<ShoppingBag/>,title:'Procurement support',copy:'Customers can send RFQs, BOQs, equipment lists or project requirements for quotation support.'},
 {icon:<ShieldCheck/>,title:'Requirement-led buying',copy:'Hardware conversations are framed around compatibility, environment, quantity and deployment needs.'}
];

export default function Page(){return <main><section className="pageHero aboutHero"><div className="container"><p className="eyebrow">About Fingaz</p><h1>A technology infrastructure partner from Computer Village, Lagos.</h1><p>Fingaz Concept Technologies Ltd supplies networking equipment, wireless connectivity hardware, CCTV/surveillance systems, access-control equipment, cabling, accessories and procurement support for businesses and projects.</p><div className="heroActions"><Link className="btn primary btnLg" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><a className="btn btnLg" href={whatsapp('Hello Fingaz, I would like to discuss a technology infrastructure requirement.')}>WhatsApp Sales</a></div></div></section><section className="section aboutSplit"><div className="container"><div><p className="overline">Who we serve</p><h2>Business buyers need more than a product list.</h2><p>Fingaz works around practical requirements: offices needing stable Wi-Fi, contractors sourcing network hardware, schools planning connectivity, hotels improving coverage, estates adding surveillance, and procurement teams comparing equipment options.</p><div className="aboutContact"><b>Direct contact</b><a href={`tel:${contact.mainLine}`}>Main line: {contact.mainLine}</a><a href={`tel:${contact.alternativeLine}`}>Alternative line: {contact.alternativeLine}</a><a href={`mailto:${contact.email}`}>{contact.email}</a></div></div><div className="aboutCards">{promises.map(p=><article key={p.title}>{p.icon}<h3>{p.title}</h3><p>{p.copy}</p></article>)}</div></div></section><section className="section aboutAssurance"><div className="container"><div className="assuranceGrid"><article><ClipboardCheck/><h2>Procurement clarity</h2><p>Fingaz helps buyers confirm model details, quantities, compatibility, warranty position and suitable alternatives before purchase.</p></article><article><Headphones/><h2>Support after supply</h2><p>Warranty and replacement conversations are handled based on the supplied model and supplier terms, with upgrade guidance where needed.</p></article></div></div></section><section className="section rfqSection aboutRfq"><div className="container"><div className="rfqPanel"><div className="rfqContent"><p className="eyebrow">How to buy</p><h2>Send what you need to source.</h2><p>Share product names, quantities, site requirements, BOQs or project notes. Fingaz can respond around availability, pricing and suitable hardware options.</p><div className="heroActions"><Link className="btn light btnLg" href="/request-quote">Send RFQ <ArrowRight size={16}/></Link><Link className="btn ghost btnLg" href="/products">Browse Products</Link></div></div><div className="rfqImage"><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=82&w=1400" alt="Professional network infrastructure"/><span>NETWORKING / SECURITY / PROCUREMENT</span></div></div></div></section></main>}