import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import {BrandStrip,CTA,IndustryGrid,ProductGrid,TrustPoint} from '@/components/ui';
import {solutions} from '@/lib/data';

export default function Home(){return <main>
<section className="hero"><div className="container heroGrid"><div><p className="eyebrow">Connectivity · Infrastructure · Security</p><h1>Infrastructure Built<br/>For Business.</h1><p className="heroCopy">Enterprise networking, wireless connectivity, surveillance and technology infrastructure for businesses across Nigeria.</p><div className="heroActions"><Link className="btn primary" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><Link className="btn ghost" href="/solutions">Explore Solutions</Link><Link className="btn ghost" href="/products">Browse Products</Link></div><div className="heroStats"><div><b>Networking</b><span>Routing, switching and structured infrastructure</span></div><div><b>Wireless</b><span>Business Wi-Fi and internet connectivity</span></div><div><b>Security</b><span>CCTV and access infrastructure</span></div></div></div><div className="networkViz" aria-label="Abstract enterprise network infrastructure visual"><span className="node one"/><span className="node two"/><span className="node three"/><span className="node four"/><div className="core">FINGAZ</div><span className="networkLabel">NETWORK / SECURITY / CONNECTIVITY</span></div></div></section>
<BrandStrip/>
<section className="section"><div className="container"><div className="sectionHead"><div><p className="overline">Core infrastructure</p><h2>Infrastructure for<br/>Every Connection.</h2></div><p>Fingaz helps organisations source the equipment that keeps networks reliable, people connected and facilities protected.</p></div><div className="editorialGrid"><Link href="/category/wireless" className="editorialCard darkCard"><p className="overline">01 / Wireless</p><h3>Wireless Connectivity</h3><p>Enterprise Wi-Fi and wireless infrastructure engineered for reliable coverage across offices, hotels and facilities.</p><span className="textLink">Explore wireless <ArrowRight size={15}/></span></Link><div className="editorialStack"><Link href="/category/networking" className="editorialCard"><p className="overline">02 / Networking</p><h3>Networking Infrastructure</h3><p className="muted">Routers, switches, gateways and structured network equipment.</p></Link><Link href="/category/security" className="editorialCard"><p className="overline">03 / Security</p><h3>Security & Surveillance</h3><p className="muted">IP CCTV, recording and monitoring infrastructure for serious environments.</p></Link></div></div></div></section>
<section className="section soft"><div className="container"><div className="sectionHead"><div><p className="overline">Solutions</p><h2>Technology Built Around<br/>Your Environment.</h2></div><Link className="textLink" href="/solutions">Explore all solutions <ArrowRight size={15}/></Link></div><div className="solutionRows">{solutions.map((s,i)=><Link className="solutionRow" href={`/solutions/${s.slug}`} key={s.slug}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.summary}</p><ArrowRight size={18}/></Link>)}</div></div></section>
<section className="section"><div className="container"><div className="sectionHead"><div><p className="overline">Product catalogue</p><h2>Specified for the job.<br/>Quoted for the project.</h2></div><p>Browse representative networking and security products, then request current pricing, availability or a formal quotation.</p></div><ProductGrid/></div></section>
<section className="section soft"><div className="container"><div className="sectionHead"><div><p className="overline">Why Fingaz</p><h2>More Than Equipment.</h2></div><p>We help businesses choose infrastructure that works together, rather than selling disconnected boxes.</p></div><div className="trustGrid"><TrustPoint title="Expert Product Selection" copy="Match equipment to the actual project requirement, environment and intended scale."/><TrustPoint title="Enterprise-Grade Brands" copy="Source hardware from globally recognised networking and security manufacturers."/><TrustPoint title="Procurement Support" copy="Build equipment lists for one-off purchases, rollouts and larger project requirements."/><TrustPoint title="Local Expertise" copy="Based in Computer Village, Ikeja, with practical knowledge of the Nigerian technology market."/></div></div></section>
<section className="section"><div className="container"><div className="procurement"><div><p className="eyebrow">Corporate procurement</p><h2>Procurement Without the Guesswork.</h2><p>Planning an office rollout, hotel network, CCTV deployment or enterprise infrastructure project? Send your equipment list or project requirements and let Fingaz help you source the right infrastructure.</p><div className="heroActions"><Link className="btn light" href="/request-quote">Submit Your RFQ <ArrowRight size={16}/></Link><Link className="btn ghost" href="/contact">Speak With Sales</Link></div></div><div className="procurementList"><div>Equipment lists & BOQs</div><div>Project requirements</div><div>Business quantities</div><div>Formal quotations</div><div>Product sourcing</div><div>Deployment guidance</div></div></div></div></section>
<section className="section soft"><div className="container"><div className="sectionHead"><div><p className="overline">Project workflow</p><h2>From Requirement<br/>to Deployment.</h2></div></div><div className="workflow"><article><span>01</span><h3>Tell Us What You Need</h3><p className="muted">Share your project scope, equipment list or environment.</p></article><article><span>02</span><h3>We Recommend the Infrastructure</h3><p className="muted">Align products and components to the requirement.</p></article><article><span>03</span><h3>Receive Your Quote</h3><p className="muted">Get current availability and project pricing.</p></article><article><span>04</span><h3>Supply & Deployment Support</h3><p className="muted">Move from sourcing into installation and deployment planning.</p></article></div></div></section>
<section className="section" id="industries"><div className="container"><div className="sectionHead"><div><p className="overline">Industries</p><h2>Infrastructure That Fits<br/>the Environment.</h2></div><p>Different sites have different demands. Fingaz supports commercial, institutional and residential technology requirements.</p></div><IndustryGrid/></div></section>
<CTA/>
</main>}
