import Link from 'next/link';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import {BrandStrip,CTA,IndustryGrid,ProductGrid,TrustPoint} from '@/components/ui';
import {solutions} from '@/lib/data';
import {userImages} from '@/lib/user-images';

const IMG={
 hero:'https://images.unsplash.com/photo-1695668548342-c0c1ad479aee?auto=format&fit=crop&q=85&w=1800',
 network:'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=82&w=1400',
 router:'https://images.unsplash.com/photo-1702895742107-35bebf49ce8b?auto=format&fit=crop&q=82&w=1200'
};

export default function Home(){return <main>
<section className="hero premiumHero"><div className="heroMedia" aria-hidden="true"><img src={IMG.hero} alt="" fetchPriority="high"/><div className="heroShade"/></div><div className="container heroGrid"><div className="heroContent"><p className="eyebrow">Connectivity · Infrastructure · Security</p><h1>Infrastructure<br/>Built for Business.</h1><p className="heroCopy">Enterprise networking, wireless connectivity, surveillance and technology infrastructure for organisations that cannot afford unreliable systems.</p><div className="heroActions"><Link className="btn primary btnLg" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><Link className="btn glassBtn btnLg" href="/solutions">Explore Solutions</Link></div><div className="heroProof"><span><CheckCircle2 size={15}/> Lagos-based infrastructure sourcing</span><span><CheckCircle2 size={15}/> Corporate RFQs & project procurement</span><span><CheckCircle2 size={15}/> Networking, wireless & surveillance</span></div></div><div className="heroPanel"><div className="heroPanelTop"><span>FINGAZ / INFRASTRUCTURE</span><span className="liveDot">Operational</span></div><div className="heroPanelBody"><p>Built around the environment.</p><h2>Networks that connect.<br/>Security that protects.<br/>Infrastructure that scales.</h2></div><div className="heroPanelFoot"><div><b>01</b><span>Networking</span></div><div><b>02</b><span>Wireless</span></div><div><b>03</b><span>Security</span></div></div></div></div></section>
<BrandStrip/>
<section className="section introSection"><div className="container"><div className="sectionHead wideHead"><div><p className="overline">What we build around</p><h2>The infrastructure<br/>behind modern business.</h2></div><p>Fingaz helps businesses choose, source and deploy the technology layer behind reliable connectivity and physical security—from the rack to the endpoint.</p></div><div className="visualMosaic"><Link href="/category/networking" className="visualCard visualLarge"><img src={IMG.network} alt="Enterprise networking rack and structured cabling" loading="lazy"/><div className="visualOverlay"/><div className="visualCopy"><span>01 / Network infrastructure</span><h3>Routing. Switching.<br/>Structured connectivity.</h3><p>Infrastructure engineered around uptime, capacity and future growth.</p><b>Explore networking <ArrowRight size={15}/></b></div></Link><div className="visualStack"><Link href="/category/security" className="visualCard userSecurityCard"><img src={userImages.cctv} alt="CCTV surveillance cameras" loading="lazy"/><div className="visualOverlay"/><div className="visualCopy"><span>02 / Security</span><h3>Surveillance that stays visible.</h3><b>Explore security <ArrowRight size={15}/></b></div></Link><Link href="/category/wireless" className="visualCard"><img src={IMG.router} alt="Business networking hardware and Ethernet connectivity" loading="lazy"/><div className="visualOverlay"/><div className="visualCopy"><span>03 / Wireless</span><h3>Coverage built for work.</h3><b>Explore wireless <ArrowRight size={15}/></b></div></Link></div></div></div></section>
<section className="section hardwareSection"><div className="container"><div className="sectionHead wideHead"><div><p className="overline">Hardware in focus</p><h2>Equipment people<br/>actually deploy.</h2></div><p>Product-led visuals, presented like infrastructure—not a cluttered electronics catalogue. Ask Fingaz for current models, availability and project pricing.</p></div><div className="hardwareShowcase"><article className="hardwareCard hardwareWhite"><div className="hardwareMedia contain"><img src={userImages.litebeam} alt="Ubiquiti LiteBeam M5 wireless equipment and packaging" loading="lazy"/></div><div className="hardwareCopy"><span>Long-range wireless</span><h3>Point-to-point connectivity.</h3><p>Wireless bridge hardware for extending connectivity between locations where conventional cabling is impractical.</p><Link className="textLink" href="/solutions/wireless-connectivity">Explore wireless solutions <ArrowRight size={15}/></Link></div></article><article className="hardwareCard hardwareDark"><div className="hardwareMedia routerMedia"><img src={userImages.router} alt="Wireless router connecting laptop phone and tablet" loading="lazy"/></div><div className="hardwareCopy"><span>Business connectivity</span><h3>Reliable Wi-Fi starts with the right hardware.</h3><p>Routers, gateways and access equipment selected around coverage, capacity and internet requirements.</p><Link className="textLink lightLink" href="/category/wireless">Browse wireless equipment <ArrowRight size={15}/></Link></div></article><article className="hardwareCard securityMini"><div className="hardwareMedia"><img src={userImages.cctv} alt="Professional security surveillance cameras" loading="lazy"/></div><div className="hardwareCopy"><span>Security infrastructure</span><h3>Visible. Managed. Scalable.</h3><p>Professional surveillance systems for offices, retail, estates and commercial facilities.</p><Link className="textLink lightLink" href="/solutions/cctv-surveillance">Explore surveillance <ArrowRight size={15}/></Link></div></article></div></div></section>
<section className="section darkSection"><div className="container"><div className="sectionHead darkHead"><div><p className="eyebrow">Solutions</p><h2>Technology built around<br/>your environment.</h2></div><Link className="textLink lightLink" href="/solutions">Explore all solutions <ArrowRight size={15}/></Link></div><div className="solutionRows premiumRows">{solutions.map((s,i)=><Link className="solutionRow" href={`/solutions/${s.slug}`} key={s.slug}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.summary}</p><ArrowRight size={18}/></Link>)}</div></div></section>
<section className="section productsSection"><div className="container"><div className="sectionHead"><div><p className="overline">Selected equipment</p><h2>Professional hardware.<br/>Project-ready sourcing.</h2></div><div><p>Browse representative products across networking, wireless and surveillance. Pricing stays quote-led because business requirements rarely fit one-size-fits-all checkout.</p><Link className="textLink sectionLink" href="/products">View all products <ArrowRight size={15}/></Link></div></div><ProductGrid/></div></section>
<section className="section soft premiumWhy"><div className="container"><div className="sectionHead"><div><p className="overline">Why Fingaz</p><h2>More than<br/>boxes on a shelf.</h2></div><p>The value is not only the equipment. It is choosing the right combination for the environment, budget, compatibility requirements and future expansion.</p></div><div className="trustGrid"><TrustPoint title="Requirement-led selection" copy="Match equipment to the actual project requirement, environment and intended scale."/><TrustPoint title="Recognised technology brands" copy="Source networking and security hardware from established global manufacturers."/><TrustPoint title="Corporate procurement support" copy="Build equipment lists for one-off purchases, multi-site rollouts and larger project requirements."/><TrustPoint title="Local technical market knowledge" copy="Based in Computer Village, Ikeja, with practical knowledge of sourcing technology in Nigeria."/></div></div></section>
<section className="section procurementSection"><div className="container"><div className="procurement premiumProcurement"><div className="procurementImage"><img src={IMG.network} alt="Network infrastructure rack prepared for enterprise deployment" loading="lazy"/><div className="procurementImageShade"/><span>ENTERPRISE PROCUREMENT / LAGOS</span></div><div className="procurementContent"><p className="eyebrow">Corporate procurement</p><h2>Send the requirement.<br/>Get the right stack.</h2><p>Planning an office rollout, hotel network, CCTV deployment or enterprise infrastructure project? Send your equipment list, BOQ or scope and let Fingaz help source the right infrastructure.</p><div className="procurementList"><div>Equipment lists & BOQs</div><div>Business quantities</div><div>Formal quotations</div><div>Product sourcing</div></div><div className="heroActions"><Link className="btn light btnLg" href="/request-quote">Submit Your RFQ <ArrowRight size={16}/></Link><Link className="btn ghost btnLg" href="/contact">Speak With Sales</Link></div></div></div></div></section>
<section className="section workflowSection"><div className="container"><div className="sectionHead"><div><p className="overline">Project workflow</p><h2>From requirement<br/>to deployment.</h2></div><p>A clear procurement path for businesses that need decisions, not product-page overload.</p></div><div className="workflow"><article><span>01</span><h3>Share the requirement</h3><p>Send your project scope, equipment list or environment.</p></article><article><span>02</span><h3>Align the infrastructure</h3><p>Match products and components to the technical requirement.</p></article><article><span>03</span><h3>Receive the quote</h3><p>Get current availability and project pricing.</p></article><article><span>04</span><h3>Supply & deployment support</h3><p>Move from sourcing into installation and rollout planning.</p></article></div></div></section>
<section className="section" id="industries"><div className="container"><div className="sectionHead"><div><p className="overline">Industries</p><h2>Infrastructure that fits<br/>the environment.</h2></div><p>Different facilities create different demands for coverage, capacity, monitoring, access and resilience.</p></div><IndustryGrid/></div></section>
<CTA/>
</main>}
