'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronDown,Menu,MessageCircle,Phone,Search as SearchIcon,ShieldCheck,X} from 'lucide-react';
import {brands,categories,contact,industries,products,Product,solutions,whatsapp} from '@/lib/data';

const productMenu=[['Server Racks & Cabinets','/category/server-racks'],['Wireless Networking','/category/wireless'],['Routers & Gateways','/products'],['Network Switches','/category/networking'],['PoE Switches','/category/network-switches'],['Fibre Modules','/category/networking-accessories'],['Power Solutions','/category/power-solutions'],['CCTV & Surveillance','/category/security'],['Access Control','/category/access-control'],['Cables & Accessories','/category/computer-accessories'],['All Products','/products']];
const navItems=[['Home','/'],['Products','/products'],['Solutions','/solutions'],['Industries','/#industries'],['About','/about'],['Contact','/contact']];

export function Navbar(){const[open,setOpen]=useState(false);const[mega,setMega]=useState<'products'|'solutions'|null>(null);return <><header className="nav"><div className="container navin"><Link href="/" className="brand" aria-label="Fingaz home">FINGAZ<span>.</span></Link><nav className="links" aria-label="Main navigation"><button className="navlink" onClick={()=>setMega(mega==='products'?null:'products')}>Products <ChevronDown size={14}/></button><button className="navlink" onClick={()=>setMega(mega==='solutions'?null:'solutions')}>Solutions <ChevronDown size={14}/></button>{navItems.slice(3).map(([l,h])=><Link key={h} href={h}>{l}</Link>)}<Search/><Link className="btn primary compact" href="/request-quote">Request Quote <ArrowRight size={15}/></Link></nav><button className="menuBtn" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div>{mega&&<div className="mega"><div className="container megaGrid"><div><p className="overline">{mega==='products'?'Product infrastructure':'Business solutions'}</p><h3>{mega==='products'?'Build the right stack.':'Start with the environment.'}</h3><p className="muted">Professional technology sourcing and project guidance from Computer Village, Lagos.</p></div><div className="megaLinks">{(mega==='products'?productMenu:solutions.map(s=>[s.title,`/solutions/${s.slug}`])).map(([label,href])=><Link key={href} href={href} onClick={()=>setMega(null)}>{label}<ArrowRight size={14}/></Link>)}</div></div></div>}{open&&<div className="mobilePanel"><div className="container mobileLinks">{navItems.map(([l,h])=><Link key={h} href={h} onClick={()=>setOpen(false)}>{l}</Link>)}<Link className="btn primary" href="/request-quote" onClick={()=>setOpen(false)}>Request a Quote</Link></div></div>}</header><div className="mobileStickyCta"><a href={`tel:${contact.mainLine}`}><Phone size={15}/> Call</a><a href={whatsapp('Hello Fingaz, I would like to request a quote.')}><MessageCircle size={15}/> WhatsApp</a><Link href="/request-quote">RFQ <ArrowRight size={14}/></Link></div></>}

export function Footer(){return <footer className="footer premiumFooter"><div className="container footerTop"><div className="footerIntro"><div className="brand light">FINGAZ<span>.</span></div><p>Networking, wireless, surveillance and IT infrastructure supply for businesses and projects across Lagos and Nigeria.</p><div className="footerCtas"><Link className="btn light compact" href="/request-quote">Request Quote</Link><a className="btn ghost compact" href={whatsapp('Hello Fingaz, I would like to discuss a technology infrastructure project.')}>WhatsApp</a></div></div><nav className="footerColumn" aria-label="Footer product links"><b>Products</b><Link href="/category/server-racks">Server Racks</Link><Link href="/category/wireless">Wireless</Link><Link href="/category/networking">Networking</Link><Link href="/category/network-switches">PoE Switches</Link><Link href="/category/networking-accessories">Fibre Modules</Link><Link href="/category/power-solutions">Power Solutions</Link><Link href="/category/security">CCTV &amp; Surveillance</Link><Link href="/category/computer-accessories">Cables &amp; Accessories</Link></nav><nav className="footerColumn" aria-label="Footer company links"><b>Company</b><Link href="/solutions">Solutions</Link><Link href="/#industries">Industries</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></nav><address className="footerColumn footerContact"><b>Contact</b><p>{contact.address[0]}<br/>{contact.address[1]}<br/>{contact.address[2]}.</p><a href={`tel:${contact.mainLine}`}>{contact.mainLine}</a><a href={`tel:${contact.alternativeLine}`}>{contact.alternativeLine}</a><a href={`mailto:${contact.email}`}>{contact.email}</a></address></div><div className="container footerBottom"><span>© {new Date().getFullYear()} Fingaz Concept Technologies Ltd.</span><span>Computer Village · Ikeja · Lagos · Nigeria</span></div></footer>}

export function ProductCard({p}:{p:Product}){const msg=`Hello Fingaz, I'm interested in the ${p.name} listed on your website. Please confirm the current price, availability and specifications.`;const image=p.images[0]||'/product.svg';const quoteHref=`/request-quote?product=${encodeURIComponent(p.name)}`;return <article className="productCard"><Link href={`/products/${p.slug}`} className="productVisual"><Image src={image} alt={p.imageAlt||`${p.name} representative product image`} fill sizes="(max-width: 640px) 100vw, (max-width: 980px) 50vw, 33vw" className="productImage"/><span className="productBrand">{p.brand}</span><span className="productType">{p.subcategory}</span></Link><div className="productBody"><div className="productMeta"><span>{categories[p.category]}</span><span>{p.availability}</span></div><Link href={`/products/${p.slug}`}><h3>{p.name}</h3></Link><p className="muted">{p.shortDescription}</p><div className="productUse"><span>Use case</span><b>{p.quoteUseCase}</b></div><div className="productActions"><Link className="textLink" href={`/products/${p.slug}`}>Quick View <ArrowRight size={14}/></Link><CompareButton id={p.id}/><Link className="textLink" href={quoteHref}>Request Quote</Link><a className="btn primary compact" href={whatsapp(msg)}><MessageCircle size={15}/> WhatsApp Enquiry</a></div></div></article>}
export function ProductGrid({items=products}:{items?:Product[]}){return <div className="productGrid">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>}
export function CompareButton({id}:{id:string}){return <button className="textButton" onClick={()=>{let arr:string[]=[];try{arr=JSON.parse(localStorage.getItem('compare')||'[]')}catch{};if(!arr.includes(id))arr=[...arr,id].slice(0,4);localStorage.setItem('compare',JSON.stringify(arr));window.dispatchEvent(new Event('compare:update'))}}>Compare</button>}

export function Search(){const[open,setOpen]=useState(false);const[q,setQ]=useState('');const results=useMemo(()=>q.trim()?products.filter(p=>(`${p.name} ${p.brand} ${p.subcategory} ${categories[p.category]} ${p.tags.join(' ')}`).toLowerCase().includes(q.toLowerCase())).slice(0,6):[],[q]);return <div className="searchbox"><button className="iconBtn" aria-label="Search products" onClick={()=>setOpen(!open)}><SearchIcon size={18}/></button>{open&&<div className="searchPanel"><div className="searchInput"><SearchIcon size={17}/><input autoFocus placeholder="Search racks, routers, SFP, PoE..." value={q} onChange={e=>setQ(e.target.value)}/></div>{q?<div className="searchResults">{results.length?results.map(p=><Link key={p.id} href={`/products/${p.slug}`} onClick={()=>{setOpen(false);setQ('')}}><span><b>{p.name}</b><small>{p.brand} · {p.subcategory}</small></span><ArrowRight size={15}/></Link>):<p className="muted">No matching products found.</p>}</div>:<p className="muted searchHint">Search the Fingaz product catalogue.</p>}</div>}</div>}

export function ProductFilter(){const[cat,setCat]=useState('');const[brand,setBrand]=useState('');const[availability,setAvailability]=useState('');const[q,setQ]=useState('');const items=products.filter(p=>(!cat||p.category===cat)&&(!brand||p.brand===brand)&&(!availability||p.availability===availability)&&(!q||(`${p.name} ${p.brand} ${p.subcategory} ${categories[p.category]} ${p.tags.join(' ')}`).toLowerCase().includes(q.toLowerCase())));return <><div className="filterBar"><label className="searchField"><SearchIcon size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></label><select value={cat} onChange={e=>setCat(e.target.value)} aria-label="Category"><option value="">All categories</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={brand} onChange={e=>setBrand(e.target.value)} aria-label="Brand"><option value="">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={availability} onChange={e=>setAvailability(e.target.value)} aria-label="Availability"><option value="">All availability</option><option>In stock</option><option>Request availability</option><option>Project order</option><option>Contact for availability</option></select></div><div className="resultCount">{items.length} product{items.length===1?'':'s'}</div><ProductGrid items={items}/></>}

export function QuoteForm(){const[done,setDone]=useState(false);const[product,setProduct]=useState('');useEffect(()=>{setProduct(new URLSearchParams(window.location.search).get('product')||'')},[]);const onSubmit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const text=`Hello Fingaz, I would like a formal quotation.\n\nName: ${form.get('name')}\nCompany: ${form.get('company')}\nPhone: ${form.get('phone')}\nEmail: ${form.get('email')}\nProject type: ${form.get('projectType')}\nProducts: ${form.get('products')}\nQuantity: ${form.get('quantity')}\nLocation: ${form.get('location')}\nRequirements: ${form.get('requirements')}`;setDone(true);window.open(whatsapp(text),'_blank','noopener,noreferrer')};return <form className="quoteForm" onSubmit={onSubmit}><div className="formgrid"><Field label="Name" name="name" required/><Field label="Company / organisation" name="company"/><Field label="Phone" name="phone" required/><Field label="WhatsApp number" name="whatsapp"/><Field label="Email" name="email" type="email" required/><label className="field">Project type<select name="projectType" required defaultValue=""><option value="" disabled>Select project type</option>{['Networking','Server Racks & Cabinets','Networking Accessories','Power Solutions','Wireless','CCTV','Access Control','Product Procurement','Structured Network','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Products required<input name="products" value={product} onChange={e=>setProduct(e.target.value)}/></label><Field label="Estimated quantity" name="quantity"/><Field label="Project location" name="location"/><label className="field full">Project description / requirements<textarea name="requirements" rows={6} required placeholder="Tell us what you are trying to deploy, the environment and any equipment list you already have."/></label></div><div className="formSubmit"><div><b>What happens next?</b><p className="muted">Your request opens in WhatsApp with the project details pre-filled so Fingaz sales can review and respond.</p></div><button className="btn primary" type="submit">Submit RFQ <ArrowRight size={16}/></button></div>{done&&<p className="success"><Check size={16}/> Your request was prepared for WhatsApp.</p>}</form>}
function Field({label,name,type='text',required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label className="field">{label}<input name={name} type={type} required={required}/></label>}

export function CompareClient(){const[ids,setIds]=useState<string[]>([]);useEffect(()=>{const load=()=>{try{const arr=JSON.parse(localStorage.getItem('compare')||'[]');setIds(Array.isArray(arr)?arr.filter((x:string)=>products.some(p=>p.id===x)):[])}catch{setIds([])}};load();addEventListener('compare:update',load);return()=>removeEventListener('compare:update',load)},[]);const items=products.filter(p=>ids.includes(p.id));if(!items.length)return <div className="emptyState"><h2>No products selected</h2><p className="muted">Choose up to four products from the catalogue to compare available specifications.</p><Link className="btn primary" href="/products">Browse products</Link></div>;const rows=['Brand','Product Type','Rack Height','Mounting','Rack Width','Cabinet Depth','Door','Power & Cooling','LTE/5G','Ethernet Ports','PoE','Management','Uplinks','Storage','Speed','Connector','Transmission Distance','Output Voltage','Capacity','Compatibility','Best For'];return <><button className="btn" onClick={()=>{localStorage.removeItem('compare');setIds([])}}>Clear comparison</button><div className="tablewrap"><table className="compare"><thead><tr><th>Specification</th>{items.map(p=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row}><th>{row}</th>{items.map(p=><td key={p.id}>{row==='Brand'?p.brand:p.specifications[row]||'Confirm for model'}</td>)}</tr>)}</tbody></table></div></>}

export function BrandStrip(){return <div className="brandStrip"><div className="container"><span>Equipment sourced across established technology brands</span><div>{brands.map(b=><strong key={b}>{b}</strong>)}</div></div></div>}
export function IndustryGrid(){return <div className="industryGrid">{industries.map((i,n)=><article key={i.name}><span>0{n+1}</span><h3>{i.name}</h3><p>{i.copy}</p><ArrowRight size={16}/></article>)}</div>}
export function CTA(){return <section className="ctaBand"><div className="ctaGlow"/><div className="container ctaGrid"><div><p className="eyebrow">Project enquiry</p><h2>Your next network starts with the right requirement.</h2><p>Talk to Fingaz about networking, wireless connectivity, surveillance, access control or technology procurement.</p></div><div className="ctaActions"><Link className="btn light btnLg" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><a className="btn ghost btnLg" href={whatsapp('Hello Fingaz, I would like to discuss a technology infrastructure project.')}>WhatsApp Fingaz</a></div></div></section>}
export function TrustPoint({title,copy}:{title:string;copy:string}){return <article className="trustPoint"><div className="trustIcon"><ShieldCheck size={21}/></div><div><h3>{title}</h3><p>{copy}</p></div></article>}
