'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronDown,Menu,Search as SearchIcon,ShieldCheck,X} from 'lucide-react';
import {brands,categories,industries,products,Product,solutions,whatsapp} from '@/lib/data';

const productMenu=[['Wireless Networking','/category/wireless'],['Routers & Gateways','/products'],['Network Switches','/category/networking'],['CCTV & Surveillance','/category/security'],['Access Control','/category/access-control'],['Cables & Accessories','/category/computer-accessories'],['All Products','/products']];

export function Navbar(){const[open,setOpen]=useState(false);const[mega,setMega]=useState<'products'|'solutions'|null>(null);return <header className="nav"><div className="container navin"><Link href="/" className="brand" aria-label="Fingaz home">FINGAZ<span>.</span></Link><nav className="links" aria-label="Main navigation"><button className="navlink" onClick={()=>setMega(mega==='products'?null:'products')}>Products <ChevronDown size={14}/></button><button className="navlink" onClick={()=>setMega(mega==='solutions'?null:'solutions')}>Solutions <ChevronDown size={14}/></button><Link href="/brands">Brands</Link><Link href="/#industries">Industries</Link><Link href="/resources">Resources</Link><Link href="/about">About</Link><Search/><Link className="btn primary compact" href="/request-quote">Request Quote <ArrowRight size={15}/></Link></nav><button className="menuBtn" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div>{mega&&<div className="mega"><div className="container megaGrid"><div><p className="overline">{mega==='products'?'Product infrastructure':'Business solutions'}</p><h3>{mega==='products'?'Build the right stack.':'Start with the environment.'}</h3><p className="muted">Professional technology sourcing and project guidance from Computer Village, Lagos.</p></div><div className="megaLinks">{(mega==='products'?productMenu:solutions.map(s=>[s.title,`/solutions/${s.slug}`])).map(([label,href])=><Link key={href} href={href} onClick={()=>setMega(null)}>{label}<ArrowRight size={14}/></Link>)}</div></div></div>}{open&&<div className="mobilePanel"><div className="container mobileLinks">{[['Products','/products'],['Solutions','/solutions'],['Brands','/brands'],['Industries','/#industries'],['Resources','/resources'],['About','/about'],['Contact','/contact']].map(([l,h])=><Link key={h} href={h} onClick={()=>setOpen(false)}>{l}</Link>)}<Link className="btn primary" href="/request-quote" onClick={()=>setOpen(false)}>Request a Quote</Link></div></div>}</header>}

export function Footer(){return <footer className="footer"><div className="container footerGrid"><div className="footerIntro"><div className="brand light">FINGAZ<span>.</span></div><p>Connectivity.<br/>Infrastructure.<br/>Security.</p><p className="footerMuted">Technology infrastructure for businesses across Lagos and Nigeria.</p></div><div><b>Products</b><Link href="/category/wireless">Wireless</Link><Link href="/category/networking">Networking</Link><Link href="/category/security">CCTV & Surveillance</Link><Link href="/category/computer-accessories">Cables & Accessories</Link></div><div><b>Company</b><Link href="/solutions">Solutions</Link><Link href="/brands">Brands</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></div><div><b>Contact</b><p>Suite 26, No. 5 Adepele Street,<br/>Computer Village, Ikeja,<br/>Lagos, Nigeria.</p><a href="tel:08175916034">0817 591 6034</a><a href="tel:08113829826">0811 382 9826</a><a href="mailto:fingazconcept@gmail.com">fingazconcept@gmail.com</a></div></div><div className="container footerBottom"><span>© {new Date().getFullYear()} Fingaz Concept Technologies Ltd.</span><span>Built for serious infrastructure enquiries.</span></div></footer>}

export function ProductCard({p}:{p:Product}){const msg=`Hello Fingaz, I'm interested in the ${p.name} listed on your website. Please confirm the current price and availability.`;return <article className="productCard"><Link href={`/products/${p.slug}`} className="productVisual"><span className="productBrand">{p.brand}</span><span className="productType">{p.subcategory}</span></Link><div className="productBody"><div className="productMeta"><span>{categories[p.category]}</span><span>{p.availability}</span></div><Link href={`/products/${p.slug}`}><h3>{p.name}</h3></Link><p className="muted">{p.shortDescription}</p><div className="productActions"><Link className="textLink" href={`/products/${p.slug}`}>View product <ArrowRight size={14}/></Link><CompareButton id={p.id}/><a className="btn primary compact" href={whatsapp(msg)}>Request Price</a></div></div></article>}
export function ProductGrid({items=products}:{items?:Product[]}){return <div className="productGrid">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>}
export function CompareButton({id}:{id:string}){return <button className="textButton" onClick={()=>{let arr:string[]=[];try{arr=JSON.parse(localStorage.getItem('compare')||'[]')}catch{};if(!arr.includes(id))arr=[...arr,id].slice(0,4);localStorage.setItem('compare',JSON.stringify(arr));window.dispatchEvent(new Event('compare:update'))}}>Compare</button>}

export function Search(){const[open,setOpen]=useState(false);const[q,setQ]=useState('');const results=useMemo(()=>q.trim()?products.filter(p=>(p.name+' '+p.brand+' '+p.tags.join(' ')).toLowerCase().includes(q.toLowerCase())).slice(0,6):[],[q]);return <div className="searchbox"><button className="iconBtn" aria-label="Search products" onClick={()=>setOpen(!open)}><SearchIcon size={18}/></button>{open&&<div className="searchPanel"><div className="searchInput"><SearchIcon size={17}/><input autoFocus placeholder="Search routers, switches, CCTV..." value={q} onChange={e=>setQ(e.target.value)}/></div>{q?<div className="searchResults">{results.length?results.map(p=><Link key={p.id} href={`/products/${p.slug}`} onClick={()=>{setOpen(false);setQ('')}}><span><b>{p.name}</b><small>{p.brand} · {p.subcategory}</small></span><ArrowRight size={15}/></Link>):<p className="muted">No matching products found.</p>}</div>:<p className="muted searchHint">Search the Fingaz product catalogue.</p>}</div>}</div>}

export function ProductFilter(){const[cat,setCat]=useState('');const[brand,setBrand]=useState('');const[availability,setAvailability]=useState('');const[q,setQ]=useState('');const items=products.filter(p=>(!cat||p.category===cat)&&(!brand||p.brand===brand)&&(!availability||p.availability===availability)&&(!q||(`${p.name} ${p.brand} ${p.subcategory} ${p.tags.join(' ')}`).toLowerCase().includes(q.toLowerCase())));return <><div className="filterBar"><label className="searchField"><SearchIcon size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></label><select value={cat} onChange={e=>setCat(e.target.value)} aria-label="Category"><option value="">All categories</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={brand} onChange={e=>setBrand(e.target.value)} aria-label="Brand"><option value="">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={availability} onChange={e=>setAvailability(e.target.value)} aria-label="Availability"><option value="">All availability</option><option>In stock</option><option>Request availability</option><option>Project order</option></select></div><div className="resultCount">{items.length} product{items.length===1?'':'s'}</div><ProductGrid items={items}/></>}

export function QuoteForm(){const[done,setDone]=useState(false);const onSubmit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const text=`Hello Fingaz, I would like a formal quotation.\n\nName: ${form.get('name')}\nCompany: ${form.get('company')}\nPhone: ${form.get('phone')}\nEmail: ${form.get('email')}\nProject type: ${form.get('projectType')}\nProducts: ${form.get('products')}\nQuantity: ${form.get('quantity')}\nLocation: ${form.get('location')}\nRequirements: ${form.get('requirements')}`;setDone(true);window.open(whatsapp(text),'_blank','noopener,noreferrer')};return <form className="quoteForm" onSubmit={onSubmit}><div className="formgrid"><Field label="Name" name="name" required/><Field label="Company / organisation" name="company"/><Field label="Phone" name="phone" required/><Field label="WhatsApp number" name="whatsapp"/><Field label="Email" name="email" type="email" required/><label className="field">Project type<select name="projectType" required defaultValue=""><option value="" disabled>Select project type</option>{['Networking','Wireless','CCTV','Access Control','Product Procurement','Structured Network','Other'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Products required" name="products"/><Field label="Estimated quantity" name="quantity"/><Field label="Project location" name="location"/><label className="field full">Project description / requirements<textarea name="requirements" rows={6} required placeholder="Tell us what you are trying to deploy, the environment and any equipment list you already have."/></label></div><div className="formSubmit"><div><b>What happens next?</b><p className="muted">Your request opens in WhatsApp with the project details pre-filled so Fingaz sales can review and respond.</p></div><button className="btn primary" type="submit">Submit RFQ <ArrowRight size={16}/></button></div>{done&&<p className="success"><Check size={16}/> Your request was prepared for WhatsApp.</p>}</form>}
function Field({label,name,type='text',required=false}:{label:string;name:string;type?:string;required?:boolean}){return <label className="field">{label}<input name={name} type={type} required={required}/></label>}

export function CompareClient(){const[ids,setIds]=useState<string[]>([]);useEffect(()=>{const load=()=>{try{const arr=JSON.parse(localStorage.getItem('compare')||'[]');setIds(Array.isArray(arr)?arr.filter((x:string)=>products.some(p=>p.id===x)):[])}catch{setIds([])}};load();addEventListener('compare:update',load);return()=>removeEventListener('compare:update',load)},[]);const items=products.filter(p=>ids.includes(p.id));if(!items.length)return <div className="emptyState"><h2>No products selected</h2><p className="muted">Choose up to four products from the catalogue to compare available specifications.</p><Link className="btn primary" href="/products">Browse products</Link></div>;const rows=['Brand','Product Type','LTE/5G','Ethernet Ports','PoE','Management','Storage'];return <><button className="btn" onClick={()=>{localStorage.removeItem('compare');setIds([])}}>Clear comparison</button><div className="tablewrap"><table className="compare"><thead><tr><th>Specification</th>{items.map(p=><th key={p.id}>{p.name}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row}><th>{row}</th>{items.map(p=><td key={p.id}>{row==='Brand'?p.brand:p.specifications[row]||'Confirm for model'}</td>)}</tr>)}</tbody></table></div></>}

export function BrandStrip(){return <div className="brandStrip"><div className="container"><span>Technology from brands businesses trust.</span><div>{brands.map(b=><strong key={b}>{b}</strong>)}</div></div></div>}
export function IndustryGrid(){return <div className="industryGrid">{industries.map((i,n)=><article key={i.name}><span>0{n+1}</span><h3>{i.name}</h3><p>{i.copy}</p></article>)}</div>}
export function CTA(){return <section className="ctaBand"><div className="container ctaGrid"><div><p className="eyebrow">Project enquiry</p><h2>Planning a Technology Infrastructure Project?</h2><p>Talk to Fingaz about networking, wireless connectivity, surveillance, access control or technology procurement.</p></div><div className="ctaActions"><Link className="btn light" href="/request-quote">Request a Quote <ArrowRight size={16}/></Link><a className="btn ghost" href={whatsapp('Hello Fingaz, I would like to discuss a technology infrastructure project.')}>WhatsApp Fingaz</a></div></div></section>}
export function TrustPoint({title,copy}:{title:string;copy:string}){return <article className="trustPoint"><ShieldCheck size={22}/><div><h3>{title}</h3><p>{copy}</p></div></article>}
