export type CategorySlug='wireless'|'networking'|'security'|'access-control'|'computer-accessories';
export type Product={id:string;slug:string;name:string;brand:string;category:CategorySlug;subcategory:string;priceLabel:string;availability:'In stock'|'Request availability'|'Project order';images:string[];description:string;shortDescription:string;features:string[];specifications:Record<string,string>;applications:string[];tags:string[];featured?:boolean};
export const categories={wireless:'Wireless Connectivity',networking:'Networking Infrastructure',security:'Security & Surveillance','access-control':'Access Control','computer-accessories':'Cables & Accessories'} as const;
export const brands=['Ubiquiti','MikroTik','Cisco','TP-Link','Hikvision','D-Link'];
export const products:Product[]=[
{id:'p1',slug:'tp-link-4g-lte-router',name:'TP-Link 4G LTE Business Router',brand:'TP-Link',category:'wireless',subcategory:'4G Router',priceLabel:'Request Price',availability:'Request availability',images:['/images/products/tp-link-archer-mr600-4g-lte-router.webp','/images/stock/router-stock-02.jpg'],description:'A business connectivity option for offices, branches and backup internet requirements. Confirm the exact model and current specifications during quotation.',shortDescription:'4G LTE connectivity for offices, branches and resilient internet setups.',features:['SIM-based internet access','Useful for failover connectivity','Business and branch deployment'],specifications:{'Product Type':'4G Router','LTE/5G':'4G LTE','Ethernet Ports':'Model dependent',Management:'Model dependent'},applications:['Office connectivity','Backup internet','Branch networks'],tags:['router','4G','TP-Link','wireless'],featured:true},
{id:'p2',slug:'ubiquiti-unifi-access-point',name:'Ubiquiti UniFi Access Point',brand:'Ubiquiti',category:'wireless',subcategory:'Access Point',priceLabel:'Request Price',availability:'Project order',images:['/images/products/ubiquiti-unifi-u6-plus-access-point.webp','/images/stock/wireless-stock-01.jpg'],description:'Managed wireless infrastructure for offices, hospitality environments and multi-access-point deployments. Final model selection depends on coverage and capacity requirements.',shortDescription:'Managed wireless access points for scalable business Wi-Fi deployments.',features:['Centralised wireless management','Scalable multi-AP deployment','Designed for professional installations'],specifications:{'Product Type':'Access Point',PoE:'Model dependent',Management:'UniFi ecosystem'},applications:['Office Wi-Fi','Hotel Wi-Fi','Estate connectivity'],tags:['access point','Ubiquiti','UniFi','Wi-Fi'],featured:true},
{id:'p3',slug:'mikrotik-routerboard-gateway',name:'MikroTik RouterBOARD Gateway',brand:'MikroTik',category:'networking',subcategory:'Router',priceLabel:'Request Price',availability:'Request availability',images:['/images/products/mikrotik-hex-rb750gr3-router.webp','/images/stock/networking-stock-01.jpg','/images/stock/router-stock-02.jpg'],description:'Configurable routing infrastructure for business networks, bandwidth management and ISP edge deployments. Exact capabilities vary by RouterBOARD model.',shortDescription:'Flexible routing and network control for SMEs, enterprises and ISPs.',features:['Advanced routing options','Bandwidth and policy controls','Flexible deployment profiles'],specifications:{'Product Type':'Router',Management:'RouterOS','Ethernet Ports':'Model dependent',PoE:'Model dependent'},applications:['Enterprise routing','SME networks','ISP edge'],tags:['router','MikroTik','RouterBOARD','networking'],featured:true},
{id:'p4',slug:'cisco-24-port-business-switch',name:'Cisco 24-Port Business Switch',brand:'Cisco',category:'networking',subcategory:'Switch',priceLabel:'Request Price',availability:'Project order',images:['/images/products/cisco-catalyst-1200-24-port-switch.webp','/images/stock/networking-stock-01.jpg'],description:'Business switching for structured network projects. Confirm the exact Cisco family, PoE requirement and uplink specification during quotation.',shortDescription:'Business-class switching for reliable wired network infrastructure.',features:['24-port switching options','PoE variants by model','Built for structured networks'],specifications:{'Product Type':'Network Switch','Ethernet Ports':'24',PoE:'Optional by model',Management:'Model dependent'},applications:['Office LAN','CCTV aggregation','Network cabinets'],tags:['Cisco','24 port switch','switch','networking'],featured:true},
{id:'p5',slug:'hikvision-ip-cctv-camera',name:'Hikvision IP CCTV Camera',brand:'Hikvision',category:'security',subcategory:'IP Camera',priceLabel:'Request Price',availability:'Request availability',images:['/images/products/hikvision-acusense-ip-dome-camera.webp'],description:'IP surveillance hardware for professional security deployments. Resolution, lens, night vision and storage requirements are specified against the site brief.',shortDescription:'IP surveillance hardware for offices, retail, estates and facilities.',features:['Professional IP surveillance','Indoor and outdoor options','Integrates with NVR and PoE infrastructure'],specifications:{'Product Type':'CCTV Camera',PoE:'Model dependent',Management:'NVR/app dependent',Storage:'Model dependent'},applications:['Retail surveillance','Office security','Warehouse monitoring'],tags:['CCTV','Hikvision','camera','security'],featured:true},
{id:'p6',slug:'d-link-cat6-network-cable',name:'D-Link Cat6 Network Cable',brand:'D-Link',category:'computer-accessories',subcategory:'Network Cable',priceLabel:'Request Price',availability:'In stock',images:['/images/products/d-link-cat6-utp-cable-roll.webp','/images/stock/cabling-stock-01.jpg'],description:'Structured cabling for LAN, CCTV and data infrastructure. Confirm length, jacket specification and project quantities during quotation.',shortDescription:'Cat6 cabling for stable wired data and surveillance infrastructure.',features:['LAN and CCTV applications','Project quantity supply','Structured cabling use'],specifications:{'Product Type':'Network Cable','Cable Class':'Cat6',PoE:'Supported when correctly installed'},applications:['Patch panels','CCTV cabling','Office LAN'],tags:['Cat6','D-Link','cable','accessories'],featured:true}
];
export type Solution={slug:string;title:string;summary:string;problem:string;points:string[];industries:string[]};
export const solutions:Solution[]=[
{slug:'enterprise-networking',title:'Enterprise Networking',summary:'Scalable routing, switching and network infrastructure for growing organisations.',problem:'Disconnected equipment and weak network design create bottlenecks as teams and sites grow.',points:['Routing and switching architecture','Network cabinets and structured deployment','Scalable equipment selection'],industries:['Corporate offices','Schools','Healthcare','Government']},
{slug:'office-wifi',title:'Office Wi-Fi',summary:'Reliable wireless coverage designed around users, floor plans and business demands.',problem:'Consumer-grade Wi-Fi often fails when coverage, roaming and concurrent users increase.',points:['Access-point planning','Managed wireless infrastructure','Coverage and capacity recommendations'],industries:['Corporate offices','Hospitality','Schools','Retail']},
{slug:'cctv-surveillance',title:'CCTV & Surveillance',summary:'Professional IP surveillance infrastructure for properties, facilities and operations.',problem:'Security systems fail when cameras, storage, switching and power are specified in isolation.',points:['IP camera selection','NVR and storage planning','PoE switching and network integration'],industries:['Retail','Warehouses','Estates','Hospitality']},
{slug:'access-control',title:'Access Control',summary:'Physical access infrastructure for offices, facilities and managed properties.',problem:'Growing organisations need better control over who can enter sensitive spaces and when.',points:['Door and entry requirements','Access device selection','Integration planning'],industries:['Corporate offices','Healthcare','Hospitality','Government']},
{slug:'wireless-internet',title:'Wireless Internet',summary:'Connectivity options for locations where conventional wired infrastructure is limited.',problem:'Some branches and sites need resilient or rapidly deployable connectivity without waiting for fixed-line infrastructure.',points:['LTE and wireless routing','Backup internet design','Site connectivity planning'],industries:['SMEs','Construction','Retail','Remote sites']},
{slug:'network-infrastructure',title:'Network Infrastructure',summary:'From cabling and racks to gateways and switching, planned as one working system.',problem:'Buying network components separately can create compatibility, capacity and maintenance problems.',points:['Structured cabling','Racks, switches and gateways','Deployment-ready equipment lists'],industries:['Offices','Hotels','Schools','Estates']}
];
export const industries=[
{name:'Corporate Offices',copy:'Secure business networking, managed Wi-Fi, surveillance and scalable infrastructure.'},
{name:'Hospitality',copy:'Guest Wi-Fi, network switching, CCTV and access infrastructure for hotels and hospitality facilities.'},
{name:'Education',copy:'Campus connectivity, classroom networking, surveillance and wireless coverage.'},
{name:'Residential Estates',copy:'Shared connectivity, surveillance and access infrastructure for modern developments.'},
{name:'Retail',copy:'Store connectivity, CCTV, switching and dependable back-office networking.'},
{name:'Healthcare',copy:'Reliable connectivity and security infrastructure for operational environments.'},
{name:'Government',copy:'Procurement and infrastructure support for public-sector technology requirements.'},
{name:'SMEs',copy:'Right-sized infrastructure that can grow without unnecessary complexity.'}
];
export type Article={slug:string;title:string;description:string;body:string[]};
export const articles:Article[]=['How to Choose the Right 4G/5G Router','Router vs Access Point: What\'s the Difference?','How Many CCTV Cameras Does Your Business Need?','Cat6 vs Cat6A: Which Network Cable Should You Buy?','How to Build a Wi-Fi Network for a Large Office','What Is PoE and Why Does Your CCTV System Need It?','How to Choose a Network Switch for Your Business'].map(t=>({slug:t.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:t,description:'A practical Fingaz guide for planning reliable technology infrastructure.',body:['Start with the business requirement, not the device. Consider coverage, capacity, security, installation environment and growth.','Before purchasing, confirm the current model, warranty, compatibility and availability for the intended deployment.']}));
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug);export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug);
const rawWhatsApp=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'2348175916034';
export const whatsappNumber=rawWhatsApp.replace(/\D/g,'');
export const whatsapp=(message:string)=>`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;
