export type CategorySlug='wireless'|'networking'|'security'|'computer-accessories';
export type Product={id:string;slug:string;name:string;brand:string;category:CategorySlug;subcategory:string;price?:number;priceLabel:string;availability:'In stock'|'Request availability'|'Project order';images:string[];description:string;shortDescription:string;features:string[];specifications:Record<string,string>;applications:string[];tags:string[]};
export const categories={wireless:'Wireless Connectivity',networking:'Networking Infrastructure',security:'Security & Surveillance','computer-accessories':'Computer Accessories'} as const;
export const brands=['TP-Link','Ubiquiti','MikroTik','Cisco','Huawei','D-Link','Hikvision','Ruijie'];
export const products:Product[]=[
{id:'p1',slug:'tp-link-4g-lte-router',name:'TP-Link 4G LTE Business Router',brand:'TP-Link',category:'wireless',subcategory:'4G Router',priceLabel:'Request Price',availability:'Request availability',images:['/product.svg'],description:'Demo inventory item for resilient office internet and branch connectivity. Confirm exact model and current specifications before purchase.',shortDescription:'4G LTE router for home, office and backup internet projects.',features:['SIM-based internet access','Suitable for failover connectivity','Quick quote via WhatsApp'],specifications:{Model:'Demo 4G LTE Router','Product Type':'4G Router','Wi-Fi Standard':'Model dependent','LTE/5G':'4G LTE','Ethernet Ports':'Model dependent',Speed:'Confirm per model',PoE:'No / model dependent',Management:'Web/app dependent',Storage:'Not applicable',Warranty:'Confirm at quote'},applications:['Home office internet','Backup connectivity','Small branch networks'],tags:['router','4G router','TP-Link','wireless']},
{id:'p2',slug:'ubiquiti-unifi-access-point',name:'Ubiquiti UniFi Access Point',brand:'Ubiquiti',category:'wireless',subcategory:'Access Point',priceLabel:'Request Price',availability:'Project order',images:['/product.svg'],description:'Demo UniFi access point listing for managed Wi-Fi deployments. Final model selection depends on coverage survey.',shortDescription:'Managed wireless access point for offices and hospitality spaces.',features:['Centralized wireless management','Scalable multi-AP deployment','Clean ceiling or wall installation'],specifications:{Model:'Demo UniFi AP','Product Type':'Access Point','Wi-Fi Standard':'Confirm per selected model','LTE/5G':'No','Ethernet Ports':'Model dependent',Speed:'Confirm per model',PoE:'Commonly PoE powered; confirm model',Management:'Controller/cloud dependent',Storage:'Not applicable',Warranty:'Confirm at quote'},applications:['Office Wi-Fi','Hotel Wi-Fi','Large home coverage'],tags:['access point','Ubiquiti','Wi-Fi','wireless']},
{id:'p3',slug:'mikrotik-routerboard-gateway',name:'MikroTik RouterBOARD Gateway',brand:'MikroTik',category:'networking',subcategory:'Router',priceLabel:'Request Price',availability:'Request availability',images:['/product.svg'],description:'Demo gateway option for routing, bandwidth control and business networks. Specifications vary by RouterBOARD model.',shortDescription:'Configurable business gateway for routing and network control.',features:['Advanced routing options','Bandwidth and policy controls','Suitable for ISP and SME networks'],specifications:{Model:'Demo RouterBOARD','Product Type':'Router','Wi-Fi Standard':'Model dependent','LTE/5G':'Optional on selected models','Ethernet Ports':'Model dependent',Speed:'Confirm per model',PoE:'Model dependent',Management:'RouterOS',Storage:'Model dependent',Warranty:'Confirm at quote'},applications:['Enterprise routing','SME networks','ISP edge deployments'],tags:['router','MikroTik','gateway','networking']},
{id:'p4',slug:'cisco-24-port-business-switch',name:'Cisco 24-Port Business Switch',brand:'Cisco',category:'networking',subcategory:'Switch',priceLabel:'Request Price',availability:'Project order',images:['/product.svg'],description:'Demo switching item for structured network projects. Confirm exact Cisco family, PoE requirement and port speeds during quote.',shortDescription:'Business-class switching for reliable wired infrastructure.',features:['24-port switching options','PoE options available by model','Designed for structured networks'],specifications:{Model:'Demo 24-Port Switch','Product Type':'Network Switch','Wi-Fi Standard':'Not applicable','LTE/5G':'No','Ethernet Ports':'24','Speed':'Confirm 1G/10G requirements','PoE':'Optional by model','Management':'Managed/unmanaged by model','Storage':'Not applicable',Warranty:'Confirm at quote'},applications:['Office LAN','CCTV aggregation','Network cabinets'],tags:['24 port switch','Cisco','switch','networking']},
{id:'p5',slug:'hikvision-ip-cctv-camera',name:'Hikvision IP CCTV Camera',brand:'Hikvision',category:'security',subcategory:'IP Camera',priceLabel:'Request Price',availability:'Request availability',images:['/product.svg'],description:'Demo IP camera for surveillance projects. Lens, resolution, night vision and storage are specified after site requirements are confirmed.',shortDescription:'IP surveillance camera for business and property security.',features:['IP surveillance deployments','Indoor/outdoor options by model','Pairs with NVR and PoE infrastructure'],specifications:{Model:'Demo IP Camera','Product Type':'CCTV Camera','Wi-Fi Standard':'Not applicable','LTE/5G':'No','Ethernet Ports':'1 by model','Speed':'Not applicable','PoE':'Model dependent','Management':'NVR/app dependent',Storage:'NVR/microSD by model','Warranty':'Confirm at quote'},applications:['Retail surveillance','Office security','Warehouse monitoring'],tags:['CCTV','camera','Hikvision','security']},
{id:'p6',slug:'d-link-cat6-network-cable',name:'D-Link Cat6 Network Cable',brand:'D-Link',category:'computer-accessories',subcategory:'Network Cable',priceLabel:'Request Price',availability:'In stock',images:['/product.svg'],description:'Demo accessory listing for structured cabling and device patching. Confirm length, jacket and installation needs.',shortDescription:'Cat6 cabling for stable wired data connections.',features:['For LAN and CCTV projects','Multiple length options','Suitable for structured cabling'],specifications:{Model:'Demo Cat6 Cable','Product Type':'Network Cable','Wi-Fi Standard':'Not applicable','LTE/5G':'No','Ethernet Ports':'Not applicable',Speed:'Cat6-class; confirm cable type','PoE':'Supports PoE when installed correctly','Management':'Not applicable',Storage:'Not applicable',Warranty:'Confirm at quote'},applications:['Patch panels','CCTV cabling','Office LAN'],tags:['Cat6','cable','D-Link','accessories']}
];
export type Solution={slug:string;title:string;summary:string;points:string[]};
export const solutions:Solution[]=[['home-office','Home & Office Connectivity'],['enterprise-networking','Enterprise Networking'],['cctv-surveillance','CCTV & Surveillance'],['access-control','Access Control'],['wireless-connectivity','Wireless Internet Solutions'],['network-infrastructure','Network Infrastructure']].map(([slug,title])=>({slug,title,summary:`Practical ${title.toLowerCase()} planning, supply and deployment support for Nigerian businesses.`,points:['Needs assessment and product selection','Network-aware installation guidance','Clear upgrade path for future growth']}));
export type Article={slug:string;title:string;description:string;body:string[]};
export const articles:Article[]=['How to Choose the Right 4G/5G Router','Router vs Access Point: What\'s the Difference?','How Many CCTV Cameras Does Your Business Need?','Cat6 vs Cat6A: Which Network Cable Should You Buy?','How to Build a Wi-Fi Network for a Large Office','What Is PoE and Why Does Your CCTV System Need It?','How to Choose a Network Switch for Your Business'].map(t=>({slug:t.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:t,description:'A practical guide from Fingaz Concept for planning reliable technology infrastructure.',body:['Start with the business requirement, not the device. Consider coverage, capacity, security, installation environment and growth.','For purchasing decisions, confirm current models, warranty status, compatibility and availability before deployment.']}));
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug); export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug);
export const whatsapp=(message:string)=>`https://wa.me/2348038027800?text=${encodeURIComponent(message)}`;
